# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d376e667bf51d9c05bf78e4cdc761455fd30fb82c53c62be00968d4493ce70cd9c14eb036421822c32d59453fb1cf614140391c52307d7cf77e99580d32976ba

test:
  secret_key_base: 939fa558a89f58c8012b14da7ba1bbcd60e850aabb251b7ed5d16105a9acf0f2652b253d30df91f68592cb2ae4ddcc15662e9ff187241913a57baf94e8b3c235

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: d1c8ff06566a5af3b41a45b98ead4935c6802e9e98aea1f74ac13c7d95b9b24c000a1e3767487e2b8b6469561fc100acbe407f32cf07ce11c0f55e433207d034
